version: "3.9"
services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
      ENVIRONMENT: testing
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    restart: always
    environment:
      POSTGRES_DB: dice-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres

volumes:
  postgres:
